<?php

namespace Database\Seeders\Tenant;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            [
                'id'         => 1,
                'name'       => 'Afghanistan',
                'short_code' => 'af',
                'predictions'=> '',
            ],
            [
                'id'         => 2,
                'name'       => 'Albania',
                'short_code' => 'al',
                'predictions'=> '',
            ],
            [
                'id'         => 3,
                'name'       => 'Algeria',
                'short_code' => 'dz',
                'predictions'=> '',
            ],
            [
                'id'         => 4,
                'name'       => 'American Samoa',
                'short_code' => 'as',
                'predictions'=> '',
            ],
            [
                'id'         => 5,
                'name'       => 'Andorra',
                'short_code' => 'ad',
                'predictions'=> '',
            ],
            [
                'id'         => 6,
                'name'       => 'Angola',
                'short_code' => 'ao',
                'predictions'=> '',
            ],
            [
                'id'         => 7,
                'name'       => 'Anguilla',
                'short_code' => 'ai',
                'predictions'=> '',
            ],
            [
                'id'         => 8,
                'name'       => 'Antarctica',
                'short_code' => 'aq',
                'predictions'=> '',
            ],
            [
                'id'         => 9,
                'name'       => 'Antigua and Barbuda',
                'short_code' => 'ag',
                'predictions'=> '',
            ],
            [
                'id'         => 10,
                'name'       => 'Argentina',
                'short_code' => 'ar',
                'predictions'=> '',
            ],
            [
                'id'         => 11,
                'name'       => 'Armenia',
                'short_code' => 'am',
                'predictions'=> '',
            ],
            [
                'id'         => 12,
                'name'       => 'Aruba',
                'short_code' => 'aw',
                'predictions'=> '',
            ],
            [
                'id'         => 13,
                'name'       => 'Australia',
                'short_code' => 'au',
                'predictions'=> '',
            ],
            [
                'id'         => 14,
                'name'       => 'Austria',
                'short_code' => 'at',
                'predictions'=> '',
            ],
            [
                'id'         => 15,
                'name'       => 'Azerbaijan',
                'short_code' => 'az',
                'predictions'=> '',
            ],
            [
                'id'         => 16,
                'name'       => 'Bahamas',
                'short_code' => 'bs',
                'predictions'=> '',
            ],
            [
                'id'         => 17,
                'name'       => 'Bahrain',
                'short_code' => 'bh',
                'predictions'=> '',
            ],
            [
                'id'         => 18,
                'name'       => 'Bangladesh',
                'short_code' => 'bd',
                'predictions'=> '',
            ],
            [
                'id'         => 19,
                'name'       => 'Barbados',
                'short_code' => 'bb',
                'predictions'=> '',
            ],
            [
                'id'         => 20,
                'name'       => 'Belarus',
                'short_code' => 'by',
                'predictions'=> '',
            ],
            [
                'id'         => 21,
                'name'       => 'Belgium',
                'short_code' => 'be',
                'predictions'=> '',
            ],
            [
                'id'         => 22,
                'name'       => 'Belize',
                'short_code' => 'bz',
                'predictions'=> '',
            ],
            [
                'id'         => 23,
                'name'       => 'Benin',
                'short_code' => 'bj',
                'predictions'=> '',
            ],
            [
                'id'         => 24,
                'name'       => 'Bermuda',
                'short_code' => 'bm',
                'predictions'=> '',
            ],
            [
                'id'         => 25,
                'name'       => 'Bhutan',
                'short_code' => 'bt',
                'predictions'=> '',
            ],
            [
                'id'         => 26,
                'name'       => 'Bolivia',
                'short_code' => 'bo',
                'predictions'=> '',
            ],
            [
                'id'         => 27,
                'name'       => 'Bosnia and Herzegovina',
                'short_code' => 'ba',
                'predictions'=> '',
            ],
            [
                'id'         => 28,
                'name'       => 'Botswana',
                'short_code' => 'bw',
                'predictions'=> '',
            ],
            [
                'id'         => 29,
                'name'       => 'Brazil',
                'short_code' => 'br',
                'predictions'=> '',
            ],
            [
                'id'         => 30,
                'name'       => 'British Indian Ocean Territory',
                'short_code' => 'io',
                'predictions'=> '',
            ],
            [
                'id'         => 31,
                'name'       => 'British Virgin Islands',
                'short_code' => 'vg',
                'predictions'=> '',
            ],
            [
                'id'         => 32,
                'name'       => 'Brunei',
                'short_code' => 'bn',
                'predictions'=> '',
            ],
            [
                'id'         => 33,
                'name'       => 'Bulgaria',
                'short_code' => 'bg',
                'predictions'=> '',
            ],
            [
                'id'         => 34,
                'name'       => 'Burkina Faso',
                'short_code' => 'bf',
                'predictions'=> '',
            ],
            [
                'id'         => 35,
                'name'       => 'Burundi',
                'short_code' => 'bi',
                'predictions'=> '',
            ],
            [
                'id'         => 36,
                'name'       => 'Cambodia',
                'short_code' => 'kh',
                'predictions'=> '',
            ],
            [
                'id'         => 37,
                'name'       => 'Cameroon',
                'short_code' => 'cm',
                'predictions'=> '',
            ],
            [
                'id'         => 38,
                'name'       => 'Canada',
                'short_code' => 'ca',
                'predictions'=> '',
            ],
            [
                'id'         => 39,
                'name'       => 'Cape Verde',
                'short_code' => 'cv',
                'predictions'=> '',
            ],
            [
                'id'         => 40,
                'name'       => 'Cayman Islands',
                'short_code' => 'ky',
                'predictions'=> '',
            ],
            [
                'id'         => 41,
                'name'       => 'Central African Republic',
                'short_code' => 'cf',
                'predictions'=> '',
            ],
            [
                'id'         => 42,
                'name'       => 'Chad',
                'short_code' => 'td',
                'predictions'=> '',
            ],
            [
                'id'         => 43,
                'name'       => 'Chile',
                'short_code' => 'cl',
                'predictions'=> '',
            ],
            [
                'id'         => 44,
                'name'       => 'China',
                'short_code' => 'cn',
                'predictions'=> '',
            ],
            [
                'id'         => 45,
                'name'       => 'Christmas Island',
                'short_code' => 'cx',
                'predictions'=> '',
            ],
            [
                'id'         => 46,
                'name'       => 'Cocos Islands',
                'short_code' => 'cc',
                'predictions'=> '',
            ],
            [
                'id'         => 47,
                'name'       => 'Colombia',
                'short_code' => 'co',
                'predictions'=> '',
            ],
            [
                'id'         => 48,
                'name'       => 'Comoros',
                'short_code' => 'km',
                'predictions'=> '',
            ],
            [
                'id'         => 49,
                'name'       => 'Cook Islands',
                'short_code' => 'ck',
                'predictions'=> '',
            ],
            [
                'id'         => 50,
                'name'       => 'Costa Rica',
                'short_code' => 'cr',
                'predictions'=> '',
            ],
            [
                'id'         => 51,
                'name'       => 'Croatia',
                'short_code' => 'hr',
                'predictions'=> '',
            ],
            [
                'id'         => 52,
                'name'       => 'Cuba',
                'short_code' => 'cu',
                'predictions'=> '',
            ],
            [
                'id'         => 53,
                'name'       => 'Curacao',
                'short_code' => 'cw',
                'predictions'=> '',
            ],
            [
                'id'         => 54,
                'name'       => 'Cyprus',
                'short_code' => 'cy',
                'predictions'=> '',
            ],
            [
                'id'         => 55,
                'name'       => 'Czech Republic',
                'short_code' => 'cz',
                'predictions'=> '',
            ],
            [
                'id'         => 56,
                'name'       => 'Democratic Republic of the Congo',
                'short_code' => 'cd',
                'predictions'=> '',
            ],
            [
                'id'         => 57,
                'name'       => 'Denmark',
                'short_code' => 'dk',
                'predictions'=> '',
            ],
            [
                'id'         => 58,
                'name'       => 'Djibouti',
                'short_code' => 'dj',
                'predictions'=> '',
            ],
            [
                'id'         => 59,
                'name'       => 'Dominica',
                'short_code' => 'dm',
                'predictions'=> '',
            ],
            [
                'id'         => 60,
                'name'       => 'Dominican Republic',
                'short_code' => 'do',
                'predictions'=> '',
            ],
            [
                'id'         => 61,
                'name'       => 'East Timor',
                'short_code' => 'tl',
                'predictions'=> '',
            ],
            [
                'id'         => 62,
                'name'       => 'Ecuador',
                'short_code' => 'ec',
                'predictions'=> '',
            ],
            [
                'id'         => 63,
                'name'       => 'Egypt',
                'short_code' => 'eg', 
                'predictions'=> implode(',',['مصر']),
            ],
            [
                'id'         => 64,
                'name'       => 'El Salvador',
                'short_code' => 'sv',
                'predictions'=> '',
            ],
            [
                'id'         => 65,
                'name'       => 'Equatorial Guinea',
                'short_code' => 'gq',
                'predictions'=> '',
            ],
            [
                'id'         => 66,
                'name'       => 'Eritrea',
                'short_code' => 'er',
                'predictions'=> '',
            ],
            [
                'id'         => 67,
                'name'       => 'Estonia',
                'short_code' => 'ee',
                'predictions'=> '',
            ],
            [
                'id'         => 68,
                'name'       => 'Ethiopia',
                'short_code' => 'et',
                'predictions'=> '',
            ],
            [
                'id'         => 69,
                'name'       => 'Falkland Islands',
                'short_code' => 'fk',
                'predictions'=> '',
            ],
            [
                'id'         => 70,
                'name'       => 'Faroe Islands',
                'short_code' => 'fo',
                'predictions'=> '',
            ],
            [
                'id'         => 71,
                'name'       => 'Fiji',
                'short_code' => 'fj',
                'predictions'=> '',
            ],
            [
                'id'         => 72,
                'name'       => 'Finland',
                'short_code' => 'fi',
                'predictions'=> '',
            ],
            [
                'id'         => 73,
                'name'       => 'France',
                'short_code' => 'fr',
                'predictions'=> '',
            ],
            [
                'id'         => 74,
                'name'       => 'French Polynesia',
                'short_code' => 'pf',
                'predictions'=> '',
            ],
            [
                'id'         => 75,
                'name'       => 'Gabon',
                'short_code' => 'ga',
                'predictions'=> '',
            ],
            [
                'id'         => 76,
                'name'       => 'Gambia',
                'short_code' => 'gm',
                'predictions'=> '',
            ],
            [
                'id'         => 77,
                'name'       => 'Georgia',
                'short_code' => 'ge',
                'predictions'=> '',
            ],
            [
                'id'         => 78,
                'name'       => 'Germany',
                'short_code' => 'de',
                'predictions'=> '',
            ],
            [
                'id'         => 79,
                'name'       => 'Ghana',
                'short_code' => 'gh',
                'predictions'=> '',
            ],
            [
                'id'         => 80,
                'name'       => 'Gibraltar',
                'short_code' => 'gi',
                'predictions'=> '',
            ],
            [
                'id'         => 81,
                'name'       => 'Greece',
                'short_code' => 'gr',
                'predictions'=> '',
            ],
            [
                'id'         => 82,
                'name'       => 'Greenland',
                'short_code' => 'gl',
                'predictions'=> '',
            ],
            [
                'id'         => 83,
                'name'       => 'Grenada',
                'short_code' => 'gd',
                'predictions'=> '',
            ],
            [
                'id'         => 84,
                'name'       => 'Guam',
                'short_code' => 'gu',
                'predictions'=> '',
            ],
            [
                'id'         => 85,
                'name'       => 'Guatemala',
                'short_code' => 'gt',
                'predictions'=> '',
            ],
            [
                'id'         => 86,
                'name'       => 'Guernsey',
                'short_code' => 'gg',
                'predictions'=> '',
            ],
            [
                'id'         => 87,
                'name'       => 'Guinea',
                'short_code' => 'gn',
                'predictions'=> '',
            ],
            [
                'id'         => 88,
                'name'       => 'Guinea-Bissau',
                'short_code' => 'gw',
                'predictions'=> '',
            ],
            [
                'id'         => 89,
                'name'       => 'Guyana',
                'short_code' => 'gy',
                'predictions'=> '',
            ],
            [
                'id'         => 90,
                'name'       => 'Haiti',
                'short_code' => 'ht',
                'predictions'=> '',
            ],
            [
                'id'         => 91,
                'name'       => 'Honduras',
                'short_code' => 'hn',
                'predictions'=> '',
            ],
            [
                'id'         => 92,
                'name'       => 'Hong Kong',
                'short_code' => 'hk',
                'predictions'=> '',
            ],
            [
                'id'         => 93,
                'name'       => 'Hungary',
                'short_code' => 'hu',
                'predictions'=> '',
            ],
            [
                'id'         => 94,
                'name'       => 'Iceland',
                'short_code' => 'is',
                'predictions'=> '',
            ],
            [
                'id'         => 95,
                'name'       => 'India',
                'short_code' => 'in',
                'predictions'=> '',
            ],
            [
                'id'         => 96,
                'name'       => 'Indonesia',
                'short_code' => 'id',
                'predictions'=> '',
            ],
            [
                'id'         => 97,
                'name'       => 'Iran',
                'short_code' => 'ir',
                'predictions'=> '',
            ],
            [
                'id'         => 98,
                'name'       => 'Iraq',
                'short_code' => 'iq',
                'predictions'=> '',
            ],
            [
                'id'         => 99,
                'name'       => 'Ireland',
                'short_code' => 'ie',
                'predictions'=> '',
            ],
            [
                'id'         => 100,
                'name'       => 'Isle of Man',
                'short_code' => 'im',
                'predictions'=> '',
            ], 
            [
                'id'         => 102,
                'name'       => 'Italy',
                'short_code' => 'it',
                'predictions'=> '',
            ],
            [
                'id'         => 103,
                'name'       => 'Ivory Coast',
                'short_code' => 'ci',
                'predictions'=> '',
            ],
            [
                'id'         => 104,
                'name'       => 'Jamaica',
                'short_code' => 'jm',
                'predictions'=> '',
            ],
            [
                'id'         => 105,
                'name'       => 'Japan',
                'short_code' => 'jp',
                'predictions'=> '',
            ],
            [
                'id'         => 106,
                'name'       => 'Jersey',
                'short_code' => 'je',
                'predictions'=> '',
            ],
            [
                'id'         => 107,
                'name'       => 'Jordan',
                'short_code' => 'jo',
                'predictions'=> '',
            ],
            [
                'id'         => 108,
                'name'       => 'Kazakhstan',
                'short_code' => 'kz',
                'predictions'=> '',
            ],
            [
                'id'         => 109,
                'name'       => 'Kenya',
                'short_code' => 'ke',
                'predictions'=> '',
            ],
            [
                'id'         => 110,
                'name'       => 'Kiribati',
                'short_code' => 'ki',
                'predictions'=> '',
            ],
            [
                'id'         => 111,
                'name'       => 'Kosovo',
                'short_code' => 'xk',
                'predictions'=> '',
            ],
            [
                'id'         => 112,
                'name'       => 'Kuwait',
                'short_code' => 'kw',
                'predictions'=> '',
            ],
            [
                'id'         => 113,
                'name'       => 'Kyrgyzstan',
                'short_code' => 'kg',
                'predictions'=> '',
            ],
            [
                'id'         => 114,
                'name'       => 'Laos',
                'short_code' => 'la',
                'predictions'=> '',
            ],
            [
                'id'         => 115,
                'name'       => 'Latvia',
                'short_code' => 'lv',
                'predictions'=> '',
            ],
            [
                'id'         => 116,
                'name'       => 'Lebanon',
                'short_code' => 'lb',
                'predictions'=> '',
            ],
            [
                'id'         => 117,
                'name'       => 'Lesotho',
                'short_code' => 'ls',
                'predictions'=> '',
            ],
            [
                'id'         => 118,
                'name'       => 'Liberia',
                'short_code' => 'lr',
                'predictions'=> '',
            ],
            [
                'id'         => 119,
                'name'       => 'Libya',
                'short_code' => 'ly',
                'predictions'=> '',
            ],
            [
                'id'         => 120,
                'name'       => 'Liechtenstein',
                'short_code' => 'li',
                'predictions'=> '',
            ],
            [
                'id'         => 121,
                'name'       => 'Lithuania',
                'short_code' => 'lt',
                'predictions'=> '',
            ],
            [
                'id'         => 122,
                'name'       => 'Luxembourg',
                'short_code' => 'lu',
                'predictions'=> '',
            ],
            [
                'id'         => 123,
                'name'       => 'Macau',
                'short_code' => 'mo',
                'predictions'=> '',
            ],
            [
                'id'         => 124,
                'name'       => 'Macedonia',
                'short_code' => 'mk',
                'predictions'=> '',
            ],
            [
                'id'         => 125,
                'name'       => 'Madagascar',
                'short_code' => 'mg',
                'predictions'=> '',
            ],
            [
                'id'         => 126,
                'name'       => 'Malawi',
                'short_code' => 'mw',
                'predictions'=> '',
            ],
            [
                'id'         => 127,
                'name'       => 'Malaysia',
                'short_code' => 'my',
                'predictions'=> '',
            ],
            [
                'id'         => 128,
                'name'       => 'Maldives',
                'short_code' => 'mv',
                'predictions'=> '',
            ],
            [
                'id'         => 129,
                'name'       => 'Mali',
                'short_code' => 'ml',
                'predictions'=> '',
            ],
            [
                'id'         => 130,
                'name'       => 'Malta',
                'short_code' => 'mt',
                'predictions'=> '',
            ],
            [
                'id'         => 131,
                'name'       => 'Marshall Islands',
                'short_code' => 'mh',
                'predictions'=> '',
            ],
            [
                'id'         => 132,
                'name'       => 'Mauritania',
                'short_code' => 'mr',
                'predictions'=> '',
            ],
            [
                'id'         => 133,
                'name'       => 'Mauritius',
                'short_code' => 'mu',
                'predictions'=> '',
            ],
            [
                'id'         => 134,
                'name'       => 'Mayotte',
                'short_code' => 'yt',
                'predictions'=> '',
            ],
            [
                'id'         => 135,
                'name'       => 'Mexico',
                'short_code' => 'mx',
                'predictions'=> '',
            ],
            [
                'id'         => 136,
                'name'       => 'Micronesia',
                'short_code' => 'fm',
                'predictions'=> '',
            ],
            [
                'id'         => 137,
                'name'       => 'Moldova',
                'short_code' => 'md',
                'predictions'=> '',
            ],
            [
                'id'         => 138,
                'name'       => 'Monaco',
                'short_code' => 'mc',
                'predictions'=> '',
            ],
            [
                'id'         => 139,
                'name'       => 'Mongolia',
                'short_code' => 'mn',
                'predictions'=> '',
            ],
            [
                'id'         => 140,
                'name'       => 'Montenegro',
                'short_code' => 'me',
                'predictions'=> '',
            ],
            [
                'id'         => 141,
                'name'       => 'Montserrat',
                'short_code' => 'ms',
                'predictions'=> '',
            ],
            [
                'id'         => 142,
                'name'       => 'Morocco',
                'short_code' => 'ma',
                'predictions'=> '',
            ],
            [
                'id'         => 143,
                'name'       => 'Mozambique',
                'short_code' => 'mz',
                'predictions'=> '',
            ],
            [
                'id'         => 144,
                'name'       => 'Myanmar',
                'short_code' => 'mm',
                'predictions'=> '',
            ],
            [
                'id'         => 145,
                'name'       => 'Namibia',
                'short_code' => 'na',
                'predictions'=> '',
            ],
            [
                'id'         => 146,
                'name'       => 'Nauru',
                'short_code' => 'nr',
                'predictions'=> '',
            ],
            [
                'id'         => 147,
                'name'       => 'Nepal',
                'short_code' => 'np',
                'predictions'=> '',
            ],
            [
                'id'         => 148,
                'name'       => 'Netherlands',
                'short_code' => 'nl',
                'predictions'=> '',
            ],
            [
                'id'         => 149,
                'name'       => 'Netherlands Antilles',
                'short_code' => 'an',
                'predictions'=> '',
            ],
            [
                'id'         => 150,
                'name'       => 'New Caledonia',
                'short_code' => 'nc',
                'predictions'=> '',
            ],
            [
                'id'         => 151,
                'name'       => 'New Zealand',
                'short_code' => 'nz',
                'predictions'=> '',
            ],
            [
                'id'         => 152,
                'name'       => 'Nicaragua',
                'short_code' => 'ni',
                'predictions'=> '',
            ],
            [
                'id'         => 153,
                'name'       => 'Niger',
                'short_code' => 'ne',
                'predictions'=> '',
            ],
            [
                'id'         => 154,
                'name'       => 'Nigeria',
                'short_code' => 'ng',
                'predictions'=> '',
            ],
            [
                'id'         => 155,
                'name'       => 'Niue',
                'short_code' => 'nu',
                'predictions'=> '',
            ],
            [
                'id'         => 156,
                'name'       => 'North Korea',
                'short_code' => 'kp',
                'predictions'=> '',
            ],
            [
                'id'         => 157,
                'name'       => 'Northern Mariana Islands',
                'short_code' => 'mp',
                'predictions'=> '',
            ],
            [
                'id'         => 158,
                'name'       => 'Norway',
                'short_code' => 'no',
                'predictions'=> '',
            ],
            [
                'id'         => 159,
                'name'       => 'Oman',
                'short_code' => 'om',
                'predictions'=> '',
            ],
            [
                'id'         => 160,
                'name'       => 'Pakistan',
                'short_code' => 'pk',
                'predictions'=> '',
            ],
            [
                'id'         => 161,
                'name'       => 'Palau',
                'short_code' => 'pw',
                'predictions'=> '',
            ],
            [
                'id'         => 162,
                'name'       => 'Palestine',
                'short_code' => 'ps',
                'predictions'=> '',
            ],
            [
                'id'         => 163,
                'name'       => 'Panama',
                'short_code' => 'pa',
                'predictions'=> '',
            ],
            [
                'id'         => 164,
                'name'       => 'Papua New Guinea',
                'short_code' => 'pg',
                'predictions'=> '',
            ],
            [
                'id'         => 165,
                'name'       => 'Paraguay',
                'short_code' => 'py',
                'predictions'=> '',
            ],
            [
                'id'         => 166,
                'name'       => 'Peru',
                'short_code' => 'pe',
                'predictions'=> '',
            ],
            [
                'id'         => 167,
                'name'       => 'Philippines',
                'short_code' => 'ph',
                'predictions'=> '',
            ],
            [
                'id'         => 168,
                'name'       => 'Pitcairn',
                'short_code' => 'pn',
                'predictions'=> '',
            ],
            [
                'id'         => 169,
                'name'       => 'Poland',
                'short_code' => 'pl',
                'predictions'=> '',
            ],
            [
                'id'         => 170,
                'name'       => 'Portugal',
                'short_code' => 'pt',
                'predictions'=> '',
            ],
            [
                'id'         => 171,
                'name'       => 'Puerto Rico',
                'short_code' => 'pr',
                'predictions'=> '',
            ],
            [
                'id'         => 172,
                'name'       => 'Qatar',
                'short_code' => 'qa',
                'predictions'=> '',
            ],
            [
                'id'         => 173,
                'name'       => 'Republic of the Congo',
                'short_code' => 'cg',
                'predictions'=> '',
            ],
            [
                'id'         => 174,
                'name'       => 'Reunion',
                'short_code' => 're',
                'predictions'=> '',
            ],
            [
                'id'         => 175,
                'name'       => 'Romania',
                'short_code' => 'ro',
                'predictions'=> '',
            ],
            [
                'id'         => 176,
                'name'       => 'Russia',
                'short_code' => 'ru',
                'predictions'=> '',
            ],
            [
                'id'         => 177,
                'name'       => 'Rwanda',
                'short_code' => 'rw',
                'predictions'=> '',
            ],
            [
                'id'         => 178,
                'name'       => 'Saint Barthelemy',
                'short_code' => 'bl',
                'predictions'=> '',
            ],
            [
                'id'         => 179,
                'name'       => 'Saint Helena',
                'short_code' => 'sh',
                'predictions'=> '',
            ],
            [
                'id'         => 180,
                'name'       => 'Saint Kitts and Nevis',
                'short_code' => 'kn',
                'predictions'=> '',
            ],
            [
                'id'         => 181,
                'name'       => 'Saint Lucia',
                'short_code' => 'lc',
                'predictions'=> '',
            ],
            [
                'id'         => 182,
                'name'       => 'Saint Martin',
                'short_code' => 'mf',
                'predictions'=> '',
            ],
            [
                'id'         => 183,
                'name'       => 'Saint Pierre and Miquelon',
                'short_code' => 'pm',
                'predictions'=> '',
            ],
            [
                'id'         => 184,
                'name'       => 'Saint Vincent and the Grenadines',
                'short_code' => 'vc',
                'predictions'=> '',
            ],
            [
                'id'         => 185,
                'name'       => 'Samoa',
                'short_code' => 'ws',
                'predictions'=> '',
            ],
            [
                'id'         => 186,
                'name'       => 'San Marino',
                'short_code' => 'sm',
                'predictions'=> '',
            ],
            [
                'id'         => 187,
                'name'       => 'Sao Tome and Principe',
                'short_code' => 'st',
                'predictions'=> '',
            ],
            [
                'id'         => 188,
                'name'       => 'Saudi Arabia',
                'short_code' => 'sa',
                'predictions'=> '',
            ],
            [
                'id'         => 189,
                'name'       => 'Senegal',
                'short_code' => 'sn',
                'predictions'=> '',
            ],
            [
                'id'         => 190,
                'name'       => 'Serbia',
                'short_code' => 'rs',
                'predictions'=> '',
            ],
            [
                'id'         => 191,
                'name'       => 'Seychelles',
                'short_code' => 'sc',
                'predictions'=> '',
            ],
            [
                'id'         => 192,
                'name'       => 'Sierra Leone',
                'short_code' => 'sl',
                'predictions'=> '',
            ],
            [
                'id'         => 193,
                'name'       => 'Singapore',
                'short_code' => 'sg',
                'predictions'=> '',
            ],
            [
                'id'         => 194,
                'name'       => 'Sint Maarten',
                'short_code' => 'sx',
                'predictions'=> '',
            ],
            [
                'id'         => 195,
                'name'       => 'Slovakia',
                'short_code' => 'sk',
                'predictions'=> '',
            ],
            [
                'id'         => 196,
                'name'       => 'Slovenia',
                'short_code' => 'si',
                'predictions'=> '',
            ],
            [
                'id'         => 197,
                'name'       => 'Solomon Islands',
                'short_code' => 'sb',
                'predictions'=> '',
            ],
            [
                'id'         => 198,
                'name'       => 'Somalia',
                'short_code' => 'so',
                'predictions'=> '',
            ],
            [
                'id'         => 199,
                'name'       => 'South Africa',
                'short_code' => 'za',
                'predictions'=> '',
            ],
            [
                'id'         => 200,
                'name'       => 'South Korea',
                'short_code' => 'kr',
                'predictions'=> '',
            ],
            [
                'id'         => 201,
                'name'       => 'South Sudan',
                'short_code' => 'ss',
                'predictions'=> '',
            ],
            [
                'id'         => 202,
                'name'       => 'Spain',
                'short_code' => 'es',
                'predictions'=> '',
            ],
            [
                'id'         => 203,
                'name'       => 'Sri Lanka',
                'short_code' => 'lk',
                'predictions'=> '',
            ],
            [
                'id'         => 204,
                'name'       => 'Sudan',
                'short_code' => 'sd',
                'predictions'=> '',
            ],
            [
                'id'         => 205,
                'name'       => 'Suriname',
                'short_code' => 'sr',
                'predictions'=> '',
            ],
            [
                'id'         => 206,
                'name'       => 'Svalbard and Jan Mayen',
                'short_code' => 'sj',
                'predictions'=> '',
            ],
            [
                'id'         => 207,
                'name'       => 'Swaziland',
                'short_code' => 'sz',
                'predictions'=> '',
            ],
            [
                'id'         => 208,
                'name'       => 'Sweden',
                'short_code' => 'se',
                'predictions'=> '',
            ],
            [
                'id'         => 209,
                'name'       => 'Switzerland',
                'short_code' => 'ch',
                'predictions'=> '',
            ],
            [
                'id'         => 210,
                'name'       => 'Syria',
                'short_code' => 'sy',
                'predictions'=> '',
            ],
            [
                'id'         => 211,
                'name'       => 'Taiwan',
                'short_code' => 'tw',
                'predictions'=> '',
            ],
            [
                'id'         => 212,
                'name'       => 'Tajikistan',
                'short_code' => 'tj',
                'predictions'=> '',
            ],
            [
                'id'         => 213,
                'name'       => 'Tanzania',
                'short_code' => 'tz',
                'predictions'=> '',
            ],
            [
                'id'         => 214,
                'name'       => 'Thailand',
                'short_code' => 'th',
                'predictions'=> '',
            ],
            [
                'id'         => 215,
                'name'       => 'Togo',
                'short_code' => 'tg',
                'predictions'=> '',
            ],
            [
                'id'         => 216,
                'name'       => 'Tokelau',
                'short_code' => 'tk',
                'predictions'=> '',
            ],
            [
                'id'         => 217,
                'name'       => 'Tonga',
                'short_code' => 'to',
                'predictions'=> '',
            ],
            [
                'id'         => 218,
                'name'       => 'Trinidad and Tobago',
                'short_code' => 'tt',
                'predictions'=> '',
            ],
            [
                'id'         => 219,
                'name'       => 'Tunisia',
                'short_code' => 'tn',
                'predictions'=> '',
            ],
            [
                'id'         => 220,
                'name'       => 'Turkey',
                'short_code' => 'tr',
                'predictions'=> '',
            ],
            [
                'id'         => 221,
                'name'       => 'Turkmenistan',
                'short_code' => 'tm',
                'predictions'=> '',
            ],
            [
                'id'         => 222,
                'name'       => 'Turks and Caicos Islands',
                'short_code' => 'tc',
                'predictions'=> '',
            ],
            [
                'id'         => 223,
                'name'       => 'Tuvalu',
                'short_code' => 'tv',
                'predictions'=> '',
            ],
            [
                'id'         => 224,
                'name'       => 'U.S. Virgin Islands',
                'short_code' => 'vi',
                'predictions'=> '',
            ],
            [
                'id'         => 225,
                'name'       => 'Uganda',
                'short_code' => 'ug',
                'predictions'=> '',
            ],
            [
                'id'         => 226,
                'name'       => 'Ukraine',
                'short_code' => 'ua',
                'predictions'=> '',
            ],
            [
                'id'         => 227,
                'name'       => 'United Arab Emirates',
                'short_code' => 'ae',
                'predictions'=> '',
            ],
            [
                'id'         => 228,
                'name'       => 'United Kingdom',
                'short_code' => 'gb',
                'predictions'=> '',
            ],
            [
                'id'         => 229,
                'name'       => 'United States',
                'short_code' => 'us',
                'predictions'=> '',
            ],
            [
                'id'         => 230,
                'name'       => 'Uruguay',
                'short_code' => 'uy',
                'predictions'=> '',
            ],
            [
                'id'         => 231,
                'name'       => 'Uzbekistan',
                'short_code' => 'uz',
                'predictions'=> '',
            ],
            [
                'id'         => 232,
                'name'       => 'Vanuatu',
                'short_code' => 'vu',
                'predictions'=> '',
            ],
            [
                'id'         => 233,
                'name'       => 'Vatican',
                'short_code' => 'va',
                'predictions'=> '',
            ],
            [
                'id'         => 234,
                'name'       => 'Venezuela',
                'short_code' => 've',
                'predictions'=> '',
            ],
            [
                'id'         => 235,
                'name'       => 'Vietnam',
                'short_code' => 'vn',
                'predictions'=> '',
            ],
            [
                'id'         => 236,
                'name'       => 'Wallis and Futuna',
                'short_code' => 'wf',
                'predictions'=> '',
            ],
            [
                'id'         => 237,
                'name'       => 'Western Sahara',
                'short_code' => 'eh',
                'predictions'=> '',
            ],
            [
                'id'         => 238,
                'name'       => 'Yemen',
                'short_code' => 'ye',
                'predictions'=> '',
            ],
            [
                'id'         => 239,
                'name'       => 'Zambia',
                'short_code' => 'zm',
                'predictions'=> '',
            ],
            [
                'id'         => 240,
                'name'       => 'Zimbabwe',
                'short_code' => 'zw',
                'predictions'=> '',
            ],
        ];

        Country::insert($countries);
    }
}
