<?php

namespace Database\Seeders\Tenant;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $i = 1;
        
        $permissions = [
            [
                'id'    => $i++,
                'title' => 'user_management_access',
                'type' => 'role.user.audit_log.user_alert',
                'parent' => 1,
            ], 
            [
                'id'    => $i++,
                'title' => 'role_create',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_edit',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_show',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_delete',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'role_access',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_create',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_edit',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_show',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_delete',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_access',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_show',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'audit_log_access',
                'type' => 'audit_log',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_create',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_show',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_delete',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'user_alert_access',
                'type' => 'user_alert',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'page_create',
                'type' => 'page',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'page_edit',
                'type' => 'page',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'page_show',
                'type' => 'page',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'page_delete',
                'type' => 'page',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'page_access',
                'type' => 'page',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'country_managment_access',
                'type' => 'country.city',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'country_create',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_edit',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_show',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_delete',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'country_access',
                'type' => 'country',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'city_create',
                'type' => 'city',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'city_edit',
                'type' => 'city',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'city_show',
                'type' => 'city',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'city_delete',
                'type' => 'city',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'city_access',
                'type' => 'city',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'product_create',
                'type' => 'product',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'product_edit',
                'type' => 'product',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'product_show',
                'type' => 'product',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'product_delete',
                'type' => 'product',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'product_access',
                'type' => 'product',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_create',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_edit',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_show',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_delete',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_access',
                'type' => 'order',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_detail_create',
                'type' => 'order_detail',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_detail_edit',
                'type' => 'order_detail',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_detail_show',
                'type' => 'order_detail',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_detail_delete',
                'type' => 'order_detail',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'order_detail_access',
                'type' => 'order_detail',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'operating_stage_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'pending_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'overview_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'prepare_delviery_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'on_delivery_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'delivered_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'returned_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'canceled_access',
                'type' => 'operating_stage',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'shift_show',
                'type' => 'shift',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'shift_access',
                'type' => 'shift',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'message_generation_access',
                'type' => 'message_generation',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'message_generation_create',
                'type' => 'message_generation',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'message_generation_show',
                'type' => 'message_generation',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'to_overview',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'to_prepare_for_delivery',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'to_on_delivery',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'to_delivered',
                'type' => 'operating_stage',
                'parent' => 2,
            ],
            [
                'id'    => $i++,
                'title' => 'to_returned',
                'type' => 'operating_stage',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'to_canceled',
                'type' => 'operating_stage',
                'parent' => 2,
            ], 
            [
                'id'    => $i++,
                'title' => 'profile_password_edit',
                'type' => 'general',
                'parent' => 2,
            ],
            
            [
                'id'    => $i++,
                'title' => 'frontend_setting_access',
                'type'  => 'slider.creative_work.service.testimonial.contactu.setting.faq_question',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_create',
                'type'  => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_edit',
                'type'  => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_show',
                'type'  => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_delete',
                'type'  => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'slider_access',
                'type'  => 'slider',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'creative_work_create',
                'type'  => 'creative_work',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'creative_work_edit',
                'type'  => 'creative_work',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'creative_work_show',
                'type'  => 'creative_work',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'creative_work_delete',
                'type'  => 'creative_work',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'creative_work_access',
                'type'  => 'creative_work',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'service_create',
                'type'  => 'service',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'service_edit',
                'type'  => 'service',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'service_show',
                'type'  => 'service',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'service_delete',
                'type'  => 'service',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'service_access',
                'type'  => 'service',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'testimonial_create',
                'type'  => 'testimonial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'testimonial_edit',
                'type'  => 'testimonial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'testimonial_show',
                'type'  => 'testimonial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'testimonial_delete',
                'type'  => 'testimonial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'testimonial_access',
                'type'  => 'testimonial',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_create',
                'type'  => 'contactu',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_edit',
                'type'  => 'contactu',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_show',
                'type'  => 'contactu',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_delete',
                'type'  => 'contactu',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'contactu_access',
                'type'  => 'contactu',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_create',
                'type'  => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_edit',
                'type'  => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_show',
                'type'  => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_delete',
                'type'  => 'setting',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'setting_access',
                'type'  => 'setting',
                'parent' => 0,
            ], 
            [
                'id'    => $i++,
                'title' => 'faq_question_create',
                'type'  => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_edit',
                'type'  => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_show',
                'type'  => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_delete',
                'type'  => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'faq_question_access',
                'type'  => 'faq_question',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_management_access',
                'type'  => 'content_category.content_tag.content_page',
                'parent' => 1,
            ],
            [
                'id'    => $i++,
                'title' => 'content_category_create',
                'type'  => 'content_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_category_edit',
                'type'  => 'content_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_category_show',
                'type'  => 'content_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_category_delete',
                'type'  => 'content_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_category_access',
                'type'  => 'content_category',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_tag_create',
                'type'  => 'content_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_tag_edit',
                'type'  => 'content_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_tag_show',
                'type'  => 'content_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_tag_delete',
                'type'  => 'content_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_tag_access',
                'type'  => 'content_tag',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_page_create',
                'type'  => 'content_page',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_page_edit',
                'type'  => 'content_page',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_page_show',
                'type'  => 'content_page',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_page_delete',
                'type'  => 'content_page',
                'parent' => 0,
            ],
            [
                'id'    => $i++,
                'title' => 'content_page_access',
                'type'  => 'content_page',
                'parent' => 0,
            ],
        ];

        Permission::insert($permissions);
    }
}
